### ISSUE TITLE
Invalid DateTime format string

### ISSUE THREAD

**Issue by ananjev-a-v** [jchristn/S3Server#1]
The src/S3Server/Constants.cs contains line 9
`internal static string AmazonTimestampFormatVerbose = "ddd, dd MMM yyy HH:mm:ss GMT";`
which should be
`internal static string AmazonTimestampFormatVerbose = "ddd, dd MMM yyy HH:mm:ss 'GMT'";`
in order avoid an unneeded substitution of M in GMT as a month number.

**Comment by jchristn** [comment]
Thank you for letting me know @ananjev-a-v I will get it fixed right now!

**Comment by jchristn** [comment]
Fixed in v6.0.0
